server:
  port: 8080

spring:
  application:
    name: bank-rest-system

  datasource:
    url: jdbc:postgresql://localhost:5433/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.xml

logging:
  level:
    com.example.bankcards: DEBUG

jwt:
  secret: dGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIGtleSBmb3IgZGV2ZWxvcG1lbnQ=
  expiration: 86400000